<div id="carousel-example-generic1" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>


    </ol>
    <div class="cabeza text-center headerMy">
        <h1>Forza e Dolcezza</h1>
    </div>
    <!-- Wrapper for slides -->
    <div class="carousel-inner carouselMy">
        <div class="item active">
            <img src="<?php echo $this->baseUrl() . '/img/patron 2 (4).jpg' ?>" alt="...">
        </div>
    </div>
</div>

<br><br><br><br>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="<?php echo $this->baseUrl() . '/img/productos/1.jpg' ?>" alt="...">
            <div class="caption">
                <h3>Producto 1</h3>
                <p>Un hermosa taza con su respectivo plato</p>
                <!-- Button trigger modal -->
                <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                    Ver producto
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="myModalLabel">Producto 1</h4>
                            </div>

                            <div class="modal-body">

                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                    <!-- Indicators -->
                                    <ol class="carousel-indicators">
                                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="3"></li>

                                    </ol>

                                    <!-- Wrapper for slides -->
                                    <div class="carousel-inner carouselModal">
                                        <div class="item active">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/1.jpg' ?>" alt="...">
                                        </div>
                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/2.jpg' ?>" alt="...">
                                        </div>
                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/4.jpg' ?>" alt="...">
                                        </div>

                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/5.jpg' ?>" alt="...">
                                        </div>

                                    </div>

                                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>


                                </div>
                                <br>
                                <p>Esta sería una descripción del producto</p>
                                <br>
                                <p>Se puede dividir en varios párrafos</p>
                            </div>
                            <div class="modal-footer">

                                <button type="button" class="btn btn-default" style="font-weight: bold" data-dismiss="modal">Precio: $213</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cerrar</button>
                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> COMPRAR</button>

                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

            </div>
        </div>
    </div>
   <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="<?php echo $this->baseUrl() . '/img/productos/1.jpg' ?>" alt="...">
            <div class="caption">
                <h3>Producto 1</h3>
                <p>Un hermosa taza con su respectivo plato</p>
                <!-- Button trigger modal -->
                <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                    Ver producto
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="myModalLabel">Producto 1</h4>
                            </div>

                            <div class="modal-body">

                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                    <!-- Indicators -->
                                    <ol class="carousel-indicators">
                                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="3"></li>

                                    </ol>

                                    <!-- Wrapper for slides -->
                                    <div class="carousel-inner carouselModal">
                                        <div class="item active">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/1.jpg' ?>" alt="...">
                                        </div>
                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/2.jpg' ?>" alt="...">
                                        </div>
                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/4.jpg' ?>" alt="...">
                                        </div>

                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/5.jpg' ?>" alt="...">
                                        </div>

                                    </div>

                                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>


                                </div>
                                <br>
                                <p>Esta sería una descripción del producto</p>
                                <br>
                                <p>Se puede dividir en varios párrafos</p>
                                <br>

                            </div>
                            <div class="modal-footer">

                                <button type="button" class="btn btn-default" style="font-weight: bold" data-dismiss="modal">Precio: $213</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cerrar</button>
                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> COMPRAR</button>

                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

            </div>
        </div>
    </div><div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="<?php echo $this->baseUrl() . '/img/productos/1.jpg' ?>" alt="...">
            <div class="caption">
                <h3>Producto 1</h3>
                <p>Un hermosa taza con su respectivo plato</p>
                <!-- Button trigger modal -->
                <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                    Ver producto
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="myModalLabel">Producto 1</h4>
                            </div>

                            <div class="modal-body">

                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                    <!-- Indicators -->
                                    <ol class="carousel-indicators">
                                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="3"></li>

                                    </ol>

                                    <!-- Wrapper for slides -->
                                    <div class="carousel-inner carouselModal">
                                        <div class="item active">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/1.jpg' ?>" alt="...">
                                        </div>
                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/2.jpg' ?>" alt="...">
                                        </div>
                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/4.jpg' ?>" alt="...">
                                        </div>

                                        <div class="item">
                                            <img src="<?php echo $this->baseUrl() . '/img/productos/5.jpg' ?>" alt="...">
                                        </div>

                                    </div>

                                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>


                                </div>
                                <br>
                                <p>Esta sería una descripción del producto</p>
                                <br>
                                <p>Se puede dividir en varios párrafos</p>
                                <br>

                            </div>
                            <div class="modal-footer">

                                <button type="button" class="btn btn-default" style="font-weight: bold" data-dismiss="modal">Precio: $213</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cerrar</button>
                                <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> COMPRAR</button>

                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

            </div>
        </div>
    </div>
</div>