<br>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        <li data-target="#carousel-example-generic" data-slide-to="5"></li>
        <li data-target="#carousel-example-generic" data-slide-to="6"></li>
        <li data-target="#carousel-example-generic" data-slide-to="7"></li>
        <li data-target="#carousel-example-generic" data-slide-to="8"></li>
        <li data-target="#carousel-example-generic" data-slide-to="9"></li>
        <li data-target="#carousel-example-generic" data-slide-to="10"></li>
    </ol>
    <div class="cabeza text-center headerMy">
        <h1>Roxana Freyra</h1>
    </div>
    <!-- Wrapper for slides -->
    <div class="carousel-inner carouselMy">
        <div class="item active">
            <img src="<?php echo $this->baseUrl() . '/img/patron 1 (1).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 1 (2).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 2 (3).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 2 (4).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 3 (6).jpg' ?>" alt="...">
        </div>

        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 4 (7).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 4 (8).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 5 (1).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 5.jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 6 (1).jpg' ?>" alt="...">
        </div>
        <div class="item">
            <img src="<?php echo $this->baseUrl() . '/img/patron 6.jpg' ?>" alt="...">
        </div>
    </div>


</div>

<br/>
<div class="row">
    <div class="col-md-4 secciones love">
        <h2 class="text-center"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'forza','action'=>'index'))?>">Forza e Dolcezza</a></h2>
        <div class="seccion">

            <img src="<?php echo $this->baseUrl() . '/img/All I need is Love.jpg' ?>" class="img-thumbnail"> 
            <h3>Concepto</h3>

            <p>Inspirada en el universo femenino, desarrolla en imágenes, formas y colores, el contraste, la dualidad o la disonancia que conviven en cada mujer…
                Siendo forza e dolcezza (fuerza y dulzura) las cualidades o características resaltadas.
                Trata de generar “armonía” en la contraposición, en el choque, en la confrontación de esas dos condiciones residentes en toda mujer. Los diseños animal print representan “la fuerza”, basándose en el instinto, la energía, la concentración, la persecución de objetivos, la acción, y hasta calificaciones no tan positivas como la intolerancia, la rudeza, etc.. Los dibujos y colores florales quieren describir la espiritualidad, la comprensión, la paz, la capacidad para amar y aceptar. 
                forza e dolcezza nació como la unión de dos aspectos opuestos, pero al desarrollar la obra, arriba a la conclusión de que son dos propiedades conectadas, relacionadas, y que su búsqueda, su descubrimiento y su aceptación pueden ser inmensamente placenteros. </p>

            <h3>Técnica</h3>

            <p>Acrílico para porcelana, cocida en horno convencional, con predominancia de texturas visuales.</p>

            </h3>Objeto</h3>

            <p>Buscando conseguir el contacto habitual, cotidiano, con el arte, se intenta plasmar en elementos comunes y populares… Hacer “arte simple”, de allí nace la idea de instalar el concepto de forza e dolcezza en artículos de uso diario como puede ser la vajilla, bajo el deseo movilizante de “respirar arte”, de encontrar arte en cada detalle.
            </p>
        </div>
    </div>
    <div class="visible-xs">
        <br>
        <hr>
        <br>
    </div>
    <div class="col-md-4 secciones forza">
        <h2 class="text-center"><a href="">Las Vueltas de la Vida</a></h2>
        <div class="seccion">

            <img src="<?php echo $this->baseUrl() . '/img/Amorinda Recortado.jpg' ?>" class="img-thumbnail">
            <h3>Concepto</h3>

            <p>Inspirada en el universo femenino, desarrolla en imágenes, formas y colores, el contraste, la dualidad o la disonancia que conviven en cada mujer…
                Siendo forza e dolcezza (fuerza y dulzura) las cualidades o características resaltadas.
                Trata de generar “armonía” en la contraposición, en el choque, en la confrontación de esas dos condiciones residentes en toda mujer. Los diseños animal print representan “la fuerza”, basándose en el instinto, la energía, la concentración, la persecución de objetivos, la acción, y hasta calificaciones no tan positivas como la intolerancia, la rudeza, etc.. Los dibujos y colores florales quieren describir la espiritualidad, la comprensión, la paz, la capacidad para amar y aceptar. 
                forza e dolcezza nació como la unión de dos aspectos opuestos, pero al desarrollar la obra, arriba a la conclusión de que son dos propiedades conectadas, relacionadas, y que su búsqueda, su descubrimiento y su aceptación pueden ser inmensamente placenteros. </p>

            <h3>Técnica</h3>

            <p>Acrílico para porcelana, cocida en horno convencional, con predominancia de texturas visuales.</p>

            </h3>Objeto</h3>

            <p>Buscando conseguir el contacto habitual, cotidiano, con el arte, se intenta plasmar en elementos comunes y populares… Hacer “arte simple”, de allí nace la idea de instalar el concepto de forza e dolcezza en artículos de uso diario como puede ser la vajilla, bajo el deseo movilizante de “respirar arte”, de encontrar arte en cada detalle.
            </p>
        </div>
    </div>
    <div class="visible-xs">
        <br>
        <hr>
        <br>
    </div>
    <div class="col-md-4 secciones vida">
        <h2 class="text-center"><a href="">Vivir en Colores</a></h2>
        <div class="seccion">

            <img src="<?php echo $this->baseUrl() . '/img/La Matanza.jpg' ?>" class="img-thumbnail">
            <h3>Concepto</h3>

            <p>Inspirada en el universo femenino, desarrolla en imágenes, formas y colores, el contraste, la dualidad o la disonancia que conviven en cada mujer…
                Siendo forza e dolcezza (fuerza y dulzura) las cualidades o características resaltadas.
                Trata de generar “armonía” en la contraposición, en el choque, en la confrontación de esas dos condiciones residentes en toda mujer. Los diseños animal print representan “la fuerza”, basándose en el instinto, la energía, la concentración, la persecución de objetivos, la acción, y hasta calificaciones no tan positivas como la intolerancia, la rudeza, etc.. Los dibujos y colores florales quieren describir la espiritualidad, la comprensión, la paz, la capacidad para amar y aceptar. 
                forza e dolcezza nació como la unión de dos aspectos opuestos, pero al desarrollar la obra, arriba a la conclusión de que son dos propiedades conectadas, relacionadas, y que su búsqueda, su descubrimiento y su aceptación pueden ser inmensamente placenteros. </p>

            <h3>Técnica</h3>

            <p>Acrílico para porcelana, cocida en horno convencional, con predominancia de texturas visuales.</p>

            </h3>Objeto</h3>

            <p>Buscando conseguir el contacto habitual, cotidiano, con el arte, se intenta plasmar en elementos comunes y populares… Hacer “arte simple”, de allí nace la idea de instalar el concepto de forza e dolcezza en artículos de uso diario como puede ser la vajilla, bajo el deseo movilizante de “respirar arte”, de encontrar arte en cada detalle.
            </p>
        </div>
    </div>
</div>