<!DOCTYPE html>
<html>
    <head>
        <title>Bootstrap 101 Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <title>Roxy Freyra</title>
        <meta  http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/css/estilos.css')
                ->prependStylesheet($this->baseUrl() . '/css/nav.css')
                ->prependStylesheet($this->baseUrl() . '/css/bootstrap.css');

        echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.10.2.min.js')
                ->appendFile($this->baseUrl() . '/js/SpasticNav.js')
                ->appendFile($this->baseUrl() . '/jquery.spasticNav.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
                ->appendFile($this->baseUrl() . '/js/frontend.js')
        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="container">
            <div class="row">
                <?php echo $this->layout()->content; ?>
            </div>

        </div>
    </body>
</html>
